codeversion

diff --git a/src/rocks-lmcompute/seedData.in b/src/rocks-lmcompute/seedData.in
--- a/src/rocks-lmcompute/seedData.in
+++ b/src/rocks-lmcompute/seedData.in
@@ -37,7 +37,9 @@ set_defaults() {
     BUILD_HASHPY=@LMHOME@/LmDbServer/tools/createClimateHashfile.py     
     
     CLIMATE_DIR=@DATADIR_SHARED@/@INPUT_LAYER_DIR@
-    CLIMATE_DB=@DATADIR_SHARED@/@INPUT_LAYER_DIR@/@INPUT_LAYER_DB@    
+    CLIMATE_DB=@DATADIR_SHARED@/@INPUT_LAYER_DIR@/@INPUT_LAYER_DB@
+    NEW_CLIMATE_DATA_DIR=$CLIMATE_DIR/$SCEN_PKG
+    
     if [ -f $CLIMATE_DB ] ; then
         EXISTING_DB=true
     else
@@ -65,7 +67,7 @@ seed_layers () {
 
 ### Retrieve climate data named in SCENARIO_PACKAGE_SEED **only** if not present
 get_climate_data () {    
-    if [ -d $CLIMATE_DIR/$SCEN_PKG ] ; then
+    if [ -d $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@ ] ; then
         echo "Climate data directory $SCEN_PKG already present" | tee -a $LOG
 
     else  
@@ -101,6 +103,20 @@ find_or_build_hashfile () {
     fi
 }
 
+fix_permissions () {
+    /bin/egrep -i "^lmwriter" /etc/passwd
+    if [ $? -ne 0 ]; then
+        echo "Error: user lmwriter does not exist" | tee -a $LOG
+        exit 1
+    fi
+
+    # This script is run by root, so set group write permission on new data dir
+    echo "Create and set group write permission on new $NEW_CLIMATE_DATA_DIR data dir"   | tee -a $LOG
+    echo "Update lmwriter group permissions on $NEW_CLIMATE_DATA_DIR" | tee -a $LOG
+    /bin/chgrp -R lmwriter $NEW_CLIMATE_DATA_DIR
+    /bin/chmod -R g+ws $NEW_CLIMATE_DATA_DIR
+}
+
 TimeStamp () {
     echo $1 `/bin/date` >> $LOG
 }
@@ -110,6 +126,7 @@ set_defaults $1
 TimeStamp "# Start"
 
 get_climate_data
+fix_permissions
 seed_layers
 
 TimeStamp "# End"
