seedData on install; script takes SCENARIO_PACKAGE arg

diff --git a/src/rocks-lmcompute/seedData.in b/src/rocks-lmcompute/seedData.in
--- a/src/rocks-lmcompute/seedData.in
+++ b/src/rocks-lmcompute/seedData.in
@@ -9,11 +9,13 @@
 
 usage () 
 {
-    echo "Usage: $0"
-    echo "This script is run after lifemapper-compute installation. It will:"
-    echo "     - download and install SCENARIO_PACKAGE_SEED data named in arguments"
-    echo "     - create ASCII grids and MXE files from the packaged TIFFs, if requested"
-    echo "     - catalog all new files (tiff, ascii, mxe)"
+    echo "Usage: $0 <SCENARIO_PACKAGE_NAME>"
+    echo "This script is run on an existing lifemapper-compute installation. "
+    echo "It will:"
+    echo "     - download and install SCENARIO_PACKAGE_NAME data from the "
+    echo "       KU Lifemapper server into the common environmental data directory"
+    echo "     - create ASCII grids and MXE files from the packaged TIFFs"
+    echo "     - catalog all original and new files in the SQLite3 database layers.db"
     echo "If the data and/or database records are present, the script will make "
     echo "only needed changes."
     echo "   "
@@ -21,16 +23,17 @@ usage ()
     echo "   "
 }
 
-if [ $# -ne 0 ]; then
+if [ $# -ne 1 ]; then
     usage
     exit 0
 fi 
 
 set_defaults() {
+    SCEN_PKG=$1
     LMURL=@LMURL@
-    CONFIG_FILE=@LMHOME@/config/config.lmcompute.ini
-    SITE_CONFIG_FILE=@LMHOME@/config/config.site.ini
+    PYBIN=/opt/python/bin/@PYTHONVER@
     SEEDPY=@LMHOME@/LmCompute/tools/layerSeeder.py
+    BUILD_HASHPY=@LMHOME@/LmDbServer/tools/createClimateHashfile.py     
     
     CLIMATE_DIR=@DATADIR_SHARED@/@INPUT_LAYER_DIR@
     CLIMATE_DB=@DATADIR_SHARED@/@INPUT_LAYER_DIR@/@INPUT_LAYER_DB@    
@@ -42,18 +45,6 @@ set_defaults() {
 
     LOG=@LMSCRATCHDISK@/log/`/bin/basename $0`.log
     touch $LOG
-
-    # get the SCENARIO_PACKAGE_SEED value from config.site.ini or config.lmserver.ini file
-    echo "Looking for climate data $SCEN_PKG"   | tee -a $LOG  
-    SCEN_PKG=`grep SCENARIO_PACKAGE_SEED $SITE_CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    if [ ! "$SCEN_PKG" ] ; then 
-        SCEN_PKG=`grep SCENARIO_PACKAGE_SEED $CONFIG_FILE | grep -v ';' | awk '{print $2}'`
-    fi
-
-    if [ ! "$SCEN_PKG" ] ; then
-        echo "SCENARIO_PACKAGE_SEED not set in $SITE_CONFIG_FILE or $CONFIG_FILE" | tee -a $LOG
-        exit 1
-    fi
 }
 
 
@@ -61,7 +52,7 @@ set_defaults() {
 seed_layers () {
     if [ -f $SEEDPY ] ; then        
         echo "Add layers for $SCEN_PKG ..." | tee -a $LOG
-        /opt/python/bin/@PYTHONVER@ $SEEDPY $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@ 2>&1 | tee -a $LOG
+        $PYBIN $SEEDPY $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@ 2>&1 | tee -a $LOG
         echo "Fix permissions on new layers.db" | tee -a $LOG
         chgrp lmwriter $CLIMATE_DB
         chmod 664 $CLIMATE_DB
@@ -73,10 +64,9 @@ seed_layers () {
 
 ### Retrieve climate data named in SCENARIO_PACKAGE_SEED **only** if not present
 get_climate_data () {    
-    # find metadata file pkgname.csv
-    if [ -f $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@ ]; then
-        echo "Climate metadata for $SCEN_PKG already present" | tee -a $LOG
-           
+    if [ -d $CLIMATE_DIR/$SCEN_PKG ] ; then
+        echo "Climate data directory $SCEN_PKG already present" | tee -a $LOG
+
     else  
         echo "Fetch climate data $SCEN_PKG" | tee -a $LOG
         curl -L "$LMURL/$SCEN_PKG.@TARBALL_POSTFIX@" -o $CLIMATE_DIR/$SCEN_PKG.@TARBALL_POSTFIX@ 
@@ -90,12 +80,32 @@ get_climate_data () {
     fi
 }
 
+### Build csv file of filehash, relativeFilename **only** if not present
+find_or_build_hashfile () {    
+    # find metadata file pkgname.csv
+    if [ -f $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@ ]; then
+        echo "Climate hash csv file for $SCEN_PKG already present" | tee -a $LOG
+           
+    # build metadata file pkgname.csv
+    else  
+        if [ -f $BUILD_HASHPY ] ; then        
+            echo "Build hash values for $SCEN_PKG ..." | tee -a $LOG
+            $PYBIN $BUILD_HASHPY  $SCEN_PKG  $CLIMATE_DIR/$SCEN_PKG 2>&1 | tee -a $LOG
+            echo "Fix permissions on new hashfile $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@" | tee -a $LOG
+            chgrp lmwriter $CLIMATE_DIR/$SCEN_PKG.@CSV_POSTFIX@
+        else
+            echo "Error: Missing file $BUILD_HASHPY" | tee -a $LOG
+            exit 1
+        fi
+    fi
+}
+
 TimeStamp () {
     echo $1 `/bin/date` >> $LOG
 }
 
 ####### Main #######
-set_defaults
+set_defaults $1
 TimeStamp "# Start"
 
 get_climate_data
